# Generated by Django 4.2 on 2023-11-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(max_length=255, verbose_name='页面角色列表')),
                ('requiresAuth', models.BooleanField(default=False, verbose_name='是否需要鉴权')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='icon图标')),
                ('locale', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='一级菜单名')),
                ('hideInMenu', models.BooleanField(blank=True, null=True, verbose_name='是否在左侧菜单中隐藏该项')),
                ('hideChildrenInMenu', models.BooleanField(blank=True, null=True, verbose_name='强制在左侧菜单中显示单项')),
                ('activeMenu', models.CharField(blank=True, max_length=255, null=True, verbose_name='高亮显示的菜单项')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='菜单项顺序')),
                ('noAffix', models.BooleanField(blank=True, null=True, verbose_name='标签是否添加到tab-bar')),
                ('ignoreCache', models.BooleanField(blank=True, null=True, verbose_name='忽略缓存')),
            ],
            options={
                'verbose_name': '路由元信息',
                'verbose_name_plural': '路由元信息',
            },
        ),
    ]
