# Generated by Django 4.2 on 2023-11-09 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_menuinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuinfo',
            name='children',
        ),
        migrations.CreateModel(
            name='ChildMenuInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='路径')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('children', models.ManyToManyField(blank=True, null=True, to='user.childmenuinfo', verbose_name='子菜单')),
                ('meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.routermeta', verbose_name='路由元信息')),
            ],
            options={
                'verbose_name': '子菜单',
                'verbose_name_plural': '子菜单',
            },
        ),
        migrations.AddField(
            model_name='menuinfo',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, to='user.childmenuinfo', verbose_name='子菜单'),
        ),
    ]
