# Generated by Django 4.2 on 2023-11-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_menuinfo_children_childmenuinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmenuinfo',
            name='children',
            field=models.ManyToManyField(blank=True, to='user.childmenuinfo', verbose_name='子菜单'),
        ),
        migrations.AlterField(
            model_name='menuinfo',
            name='children',
            field=models.ManyToManyField(blank=True, to='user.childmenuinfo', verbose_name='子菜单'),
        ),
    ]
