# Generated by Django 4.2 on 2023-11-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_childmenuinfo_children_alter_menuinfo_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routermeta',
            name='roles',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='页面角色列表'),
        ),
    ]
