# Generated by Django 4.2 on 2023-11-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_routermeta_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routermeta',
            name='locale',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='locale'),
        ),
    ]
