# Generated by Django 4.2 on 2023-11-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_routermeta_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accountId',
            field=models.CharField(blank=True, default='13824464121', max_length=255, null=True, verbose_name='账号id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, default='做音乐，艺术家！', null=True, verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, default='SoftJob', max_length=255, null=True, verbose_name='工作'),
        ),
        migrations.AlterField(
            model_name='user',
            name='jobName',
            field=models.CharField(blank=True, default='软件开发负责人', max_length=255, null=True, verbose_name='工作名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.TextField(blank=True, default='ShangHai', null=True, verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locationName',
            field=models.TextField(blank=True, default='上海', null=True, verbose_name='位置名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personalWebsite',
            field=models.URLField(blank=True, default='https://github.com/huifeng-kooboo', null=True, verbose_name='个人网站'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(auto_created=True, blank=True, default='13824464121', help_text='手机号', max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('管理员', 'admin'), ('普通用户', 'user')], default='admin', max_length=255, null=True, verbose_name='角色'),
        ),
    ]
