# Generated by Django 4.2 on 2023-12-08 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_child_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sub_channel_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sub_channel_ids',
        ),
    ]
