# Generated by Django 5.1.1 on 2024-11-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, default='semester 1', max_length=250, null=True, verbose_name='semester'),
        ),
    ]
