# Generated by Django 4.2 on 2023-12-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_type', models.IntegerField(choices=[('护肤产品', 1), ('食品药品', 2), ('彩妆', 3), ('日用品', 4), ('其他', 5)], verbose_name='商品种类')),
                ('goods_name', models.CharField(default='SK2', max_length=255, unique=True, verbose_name='商品名称')),
                ('goods_image', models.ImageField(upload_to='static', verbose_name='商品图片')),
                ('price', models.IntegerField(default=0, verbose_name='商品价格[人民币]')),
                ('inventory', models.IntegerField(default=0, verbose_name='商品库存[个数]')),
                ('is_online', models.BooleanField(default=True, verbose_name='是否上架[默认上架]')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
    ]
