# Generated by Django 4.2 on 2023-12-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_type',
            field=models.IntegerField(choices=[(1, '护肤产品'), (2, '食品药品'), (3, '彩妆'), (4, '日用品'), (5, '其他')], verbose_name='商品种类'),
        ),
    ]
