# Generated by Django 4.2 on 2023-12-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_goodsinfo_goods_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_image',
            field=models.ImageField(upload_to='static/goods_images', verbose_name='商品图片'),
        ),
    ]
