# Generated by Django 4.2 on 2024-09-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_goodsinfo_goods_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BachorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type', models.IntegerField(default=0, verbose_name='类型')),
                ('name', models.TextField(default='', verbose_name='内容')),
            ],
            options={
                'verbose_name': '信息表',
                'verbose_name_plural': '信息表',
            },
        ),
        migrations.CreateModel(
            name='SubjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(default='', max_length=100, verbose_name='科目')),
                ('code', models.CharField(default='', max_length=10, verbose_name='科目代码')),
                ('primary_info', models.CharField(default='', max_length=100, verbose_name='primary info')),
                ('credit_points', models.IntegerField(default=0, verbose_name='credit points')),
                ('subject_url', models.CharField(default='', max_length=100, verbose_name='subject url')),
            ],
            options={
                'verbose_name': 'info',
                'verbose_name_plural': 'info',
            },
        ),
        migrations.DeleteModel(
            name='GoodsInfo',
        ),
    ]
