# Generated by Django 4.2 on 2023-11-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(default='default', max_length=255, unique=True, verbose_name='工作名称')),
                ('job_id', models.CharField(default='None', editable=False, max_length=255, verbose_name='job_id')),
                ('is_start', models.BooleanField(default=False, verbose_name='是否开始工作')),
            ],
            options={
                'verbose_name': 'Job控制器',
                'verbose_name_plural': 'Job控制器',
            },
        ),
    ]
