# Generated by Django 4.2 on 2024-10-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BachorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type', models.IntegerField(default=0, verbose_name='Type')),
                ('name', models.TextField(default='', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'BachorInfo',
                'verbose_name_plural': 'BachorInfo',
            },
        ),
        migrations.CreateModel(
            name='SubjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(default='', max_length=100, verbose_name='Subject')),
                ('code', models.CharField(default='', max_length=10, verbose_name='Subject Code')),
                ('primary_info', models.CharField(default='', max_length=100, verbose_name='primary info')),
                ('credit_points', models.IntegerField(default=0, verbose_name='credit points')),
                ('subject_url', models.CharField(default='', max_length=100, verbose_name='subject url')),
            ],
            options={
                'verbose_name': 'SubjectInfo',
                'verbose_name_plural': 'SubjectInfo',
            },
        ),
    ]
