# Generated by Django 4.2 on 2024-10-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='name')),
                ('subject_name', models.CharField(default='', max_length=100, verbose_name='Subject')),
                ('content', models.CharField(default='', max_length=250, verbose_name='SubjectContent')),
                ('is_checked', models.BooleanField(default=False, verbose_name='isCheck')),
                ('semester', models.CharField(default='', max_length=250, verbose_name='semester')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Template',
            },
        ),
    ]
